version: '3'

services:
  app:
    build: .
    environment:
      REDIS_URL: 'redis'
      REDIS_PORT: 6379
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:4.0
    ports:
      - "6379"
